config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'

  resources :contacts, only: [:index, :new, :create]

  resources :educational_services, only: [:index]

  resources :blogs

  resources :store, only: [:index]

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_one :user
  attachment :blog_image

end

app/models/blog_email.rb
class BlogEmail < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_emails_controller.rb
class BlogEmailsController < ApplicationController
  def idex

  end

  def new
    @blog_email = BlogEmail.new
  end

  def create
    @blog_email = BlogEmail.new(blog_email_params)

    if @blog_email.save
      redirect_to root_path

    else
      render 'new'
    end
  end

  private
  def blog_email_params
    params.require(:blog_email).permit(:display_name, :email)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :find_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @blogs = Blog.order('created_at DESC').page(params[:page]).per(10)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to blogs_path

    else
      render 'new'
    end
  end

  def show

  end

  def update
    if @blog.update(blog_params)
      redirect_to blog_path(@blog)
    else
      render 'edit'
    end
  end

  def edit

  end

  def find_blog
    @blog = Blog.find(params[:id])
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path
  end
    private

    def blog_params
      params.require(:blog).permit(:title, :entry,:blog_image)
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to root_path

    else
      render 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:display_name, :email, :phone, :message)
  end
end

app/controllers/educational_services_controller.rb
class EducationalServicesController < ApplicationController
  def idex
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index

  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/blog_helper.rb
module BlogHelper
  def markdown
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :hard_wrap => true, :filter_html => true)
  end
end

app/helpers/butter_helper.rb
module ButterHelper
end

app/views/blogs/_form.html.erb
<div class="col-lg-offset-2 col-lg-8">
  <%= simple_form_for @blog do |f| %>
  <%= f.input  :title, label: "Title of post", :input_html => {:style=> 'width: 300px'}%>
  <%= f.attachment_field :blog_image, direct: true %>
  <%= f.input  :entry, label: "Blog Entry", :input_html => {:style=> 'width: 600px', :rows => 10}%>
  <%= f.button :submit, "Submit" %>
  <% end %>
</div><!-- col-lg -->

app/views/blogs/edit.html.erb
<br>
<br>
<center>
  <h2>Edit Blog Post</h2>
</center>
<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="title">
  <p>
    ODCA's Blog
  </p>
  <% if user_signed_in? && current_user.admin? %>
    <%=link_to "New Post", new_blog_path %>
  <% end %>
</div>
<% @blogs.each do |blog| %>
<% @blog = blog %>
  <div class="col-md-8 col-md-offset-2 blog-title">
    <h2><%= blog.title %></h2>
  </div>
  <div class="col-md-8 col-md-offset-2 blogpost">
    <p>
      <%= markdown.render(truncate blog.entry, length: 400).html_safe %>
    </p>
    <%= link_to 'Read More', blog_path(blog) %>
  </div>
<% end %>
<div class="paginate">
  <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<br>
<br>
<center>
  <h2>New Blog Post</h2>
</center>
<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="title">
  <p>
    <%= @blog.title %>
  </p>
  <% if user_signed_in? && current_user.admin? %>
    <%=link_to "Edit Post", edit_blog_path(@blog) %>
    <%=link_to "Delete Post", blog_path(@blog), method: :delete, data: { confirm: "Are you sure you want to delete?"}%>
  <% end %>
    <%=link_to "Back To Blog", blogs_path %>
</div>

<div class="col-md-8 col-md-offset-2 picture">
  <%= image_tag attachment_url(@blog, :blog_image), :class => "style_image img-responsive" %>
</div>

<div class="col-md-8 col-md-offset-2 post">

  <p>
    <br>
    <%= @blog.created_at.strftime("%B %d, %Y") %>
  </p>
  <p>
    <%= markdown.render(@blog.entry).html_safe %>
  </p>
  <p class='bottom'>
  </p>
</div>

app/views/contacts/_form.html.erb
<div class="col-lg-offset-2 col-lg-8 contact">
  <%= simple_form_for @contact do |f| %>
  <%= f.input  :display_name, label: "Name:", :input_html => {:style=> 'width: 600px'}%>
  <%= f.input  :email, label: "Email Address:", :input_html => {:style=> 'width: 600px'}%>
  <%= f.input  :phone, label: "Phone Number:", :input_html => {:style=> 'width: 600px'}%>
  <%= f.input  :message, label: "Your Message:", :input_html => {:style=> 'width: 600px', :rows => 7}%>
  <%= f.button :submit, "Submit" %>
  <% end %>
</div><!-- col-lg -->

app/views/contacts/new.html.erb
<br>
<br>
<div class='title'>
  <center>
    <h2>Contact Us</h2>
</div>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ODCA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="container">
    <div id="custom-bootstrap-menu" class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header"><a class="navbar-brand" href="/"><%= image_tag('logo3.png') %></a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/educational_services">Educational Programs</a>
            </li>
            <li><a href="/blogs">Blog</a>
            </li>
            <li><a href="/store">Store</a>
            </li>
            <li><a href="/contacts/new">Contact Us</a>
            </li>
            <% if user_signed_in?%>
              <li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>



<%= yield %>

  <div class="navbar navbar-default navbar-fixed-bottom bottom">
    <div class="container">

      <ul class="nav navbar-nav navbar-right">
        <li class='facebook'><a href="https://www.facebook.com/Oceans-Daughter-Conservation-Alliance-351791464953076/" target="_blank"><i class="fa fa-facebook-official fa-2x"></i></a>
        </li>
        <li class='twitter'><a href="https://twitter.com/odcamermaid" target="_blank"><i class="fa fa-twitter fa-2x"></i></a>
        </li>
      </ul></div>
  </div>
</body>
</html>

app/views/store/index.html.erb
<div id="header">
  <p>
    ODCA's Store <br>
    Coming Soon!
  </p>
</div>